### ISSUE TITLE
Crear una consulta para escoger el auxiliar veterinario que se le asignará al paciente

### ISSUE THREAD

**Issue by EstefaniaSierra** [joanvarso/hosvet_loscuatro#25]

**Comment by Wilsonfelipehernandez** [comment]
<img width="798" alt="consulta1" src="https://user-images.githubusercontent.com/91097343/134756000-24ffb8a4-c29f-480f-8410-79582f54db47.PNG">
<img width="824" alt="consulta2" src="https://user-images.githubusercontent.com/91097343/134756001-870bc6fa-708c-408f-badf-bf010d8222f8.PNG">

**Comment by Wilsonfelipehernandez** [comment]
adjunto Crear una consulta para escoger el auxiliar veterinario que se le asignará al paciente
